name = "makanmakan-customer"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
pages_build_output_dir = "dist"
pages_build_command = "npm run build"

[env.staging]
name = "makanmakan-customer-staging"
pages_build_output_dir = "dist"
pages_build_command = "npm run build"