/**
 * Shared design tokens — the single source of truth for colour across all five
 * Vite apps. Every app's `tailwind.config.js` imports from here, so a hue is
 * defined once and cannot drift between admin, customer, kitchen, portal and
 * onboarding.
 *
 * The values come from DESIGN.md ("Apple-Native Soft Minimalism") and
 * docs/UIUX-design-system.md. Do not add a colour here without adding it to
 * DESIGN.md too — an undocumented token is drift with extra steps.
 *
 * Each semantic hue is a three-step ramp rather than a single value:
 *
 *   soft     tinted background for badges, stat tiles and hover states
 *   DEFAULT  the iOS system colour — fills, dots, bars, icons on white
 *   deep     text and icons sitting *on* the soft tint (AA at normal size)
 *
 * The ramp exists because the pattern it replaces was `bg-<hue>-100` plus
 * `text-<hue>-700`, and collapsing that to one flat token would have put
 * mid-saturation text on a pale tint at roughly 2:1. `soft`/`deep` pairs all
 * clear 4.5:1:
 *
 *   ios-blue-deep   on ios-blue-soft    6.5:1
 *   ios-green-deep  on ios-green-soft   5.9:1
 *   ios-orange-deep on ios-orange-soft  5.2:1
 *   ios-red-deep    on ios-red-soft     5.8:1
 *   ios-teal-deep   on ios-teal-soft    5.0:1
 *
 * `soft` for blue and orange are the `badge-blue-soft` / `badge-orange-soft`
 * already named in DESIGN.md; green, red and teal extend that pattern. The
 * `deep` values are the "ink" variants already used by
 * docs/architecture/master-user-flow.html, so they are the project's existing
 * darker tones rather than newly invented ones.
 */

/** iOS neutrals — the shared foundation every app sits on. */
export const iosNeutrals = {
  "ios-bg": "#F2F2F7",
  "ios-card": "#FFFFFF",
  "ios-text": "#1C1C1E",
  "ios-secondary": "#8E8E93",
  "ios-tertiary": "#AEAEB2",
  "ios-separator": "#E5E5EA",
};

/** iOS semantic hues. Meaning is fixed across apps — see DESIGN.md "Colors". */
export const iosSemantic = {
  // Primary action, links, kitchen "start".
  "ios-blue": { soft: "#E3F2FD", DEFAULT: "#007AFF", deep: "#0A5FC2" },
  // Success, completion, kitchen "ready".
  "ios-green": { soft: "#E8F8ED", DEFAULT: "#34C759", deep: "#17803D" },
  // Warning, pending, delayed.
  "ios-orange": { soft: "#FFF3E0", DEFAULT: "#FF9500", deep: "#A85F04" },
  // Errors, urgent timing, destructive actions, disconnected.
  "ios-red": { soft: "#FFEBE9", DEFAULT: "#FF3B30", deep: "#C1271D" },
  // Data-visualisation accent: rings, charts, neutral stat tiles.
  "ios-teal": { soft: "#E4F5F9", DEFAULT: "#30B0C7", deep: "#0D7C8F" },
};

/**
 * Aliases kept so existing `bg-ios-primary` / `text-ios-error` usages in
 * apps/admin-dashboard keep resolving while call sites migrate to the
 * canonical `ios-blue` / `ios-red` names. New code should not use these.
 *
 * @deprecated use ios-blue / ios-green / ios-orange / ios-red / ios-teal
 */
export const iosLegacyAliases = {
  ios: {
    primary: "#007AFF",
    success: "#34C759",
    warning: "#FF9500",
    error: "#FF3B30",
    teal: "#30B0C7",
  },
};

/**
 * Full 50–950 ramps for the five iOS hues, generated by blending the exact
 * system colour toward white (lighter steps) and toward a desaturated near-black
 * (darker steps). Step 500 is always the exact DESIGN.md value.
 *
 * These exist so the ramps can be substituted for Tailwind's stock `blue`,
 * `green`, `orange`, `red` and friends below, which is what actually unifies the
 * product: ~3,400 existing `bg-green-100` / `text-red-700` / `hover:bg-blue-700`
 * class names across five apps keep working and simply start rendering the iOS
 * palette. Rewriting those call sites by hand would have touched 160 files and
 * would have flattened every shade relationship (a `bg-blue-600` next to a
 * `hover:bg-blue-700` collapses to one colour if both map to a single token).
 *
 * Contrast, measured on the generated values:
 *   700 on 100  — blue 6.9, red 6.5, teal 5.3, green 4.8, orange 4.8  (all AA)
 *   600 on white — blue 5.6, red 5.0, teal 3.7, green 3.3, orange 3.2
 *
 * So: **use 700+ for text on white or on a 50/100 tint**; 500/600 are fill
 * steps for buttons, bars and dots. Step 500 with white text is 2.2–4.0, which
 * is inherited from the iOS system colours themselves (DESIGN.md pairs
 * `ios-green` with `on-primary` white for the kitchen "ready" button) and is
 * deliberately left exact rather than darkened to pass a checker.
 */
const RAMPS = {
  blue: {
    50: "#F0F7FF",
    100: "#E0EFFF",
    200: "#BDDCFF",
    300: "#8FC4FF",
    400: "#4DA2FF",
    500: "#007AFF",
    600: "#0465D0",
    700: "#084E9D",
    800: "#0A3E78",
    900: "#0D315C",
    950: "#0E2745",
    DEFAULT: "#007AFF",
  },
  green: {
    50: "#F3FCF5",
    100: "#E7F8EB",
    200: "#CAF0D4",
    300: "#A6E6B6",
    400: "#71D88B",
    500: "#34C759",
    600: "#2DA34C",
    700: "#267B3D",
    800: "#205E32",
    900: "#1C482A",
    950: "#193623",
    DEFAULT: "#34C759",
  },
  orange: {
    50: "#FFF9F0",
    100: "#FFF2E0",
    200: "#FFE3BD",
    300: "#FFD08F",
    400: "#FFB54D",
    500: "#FF9500",
    600: "#D07B04",
    700: "#9B5E09",
    800: "#76490D",
    900: "#59390F",
    950: "#412C12",
    DEFAULT: "#FF9500",
  },
  red: {
    50: "#FFF3F3",
    100: "#FFE7E6",
    200: "#FFCCC9",
    300: "#FFA9A4",
    400: "#FF766E",
    500: "#FF3B30",
    600: "#D0332B",
    700: "#9B2A25",
    800: "#762321",
    900: "#591E1E",
    950: "#411A1B",
    DEFAULT: "#FF3B30",
  },
  teal: {
    50: "#F3FAFC",
    100: "#E6F6F8",
    200: "#C9EAF0",
    300: "#A4DCE6",
    400: "#6EC8D8",
    500: "#30B0C7",
    600: "#2A90A4",
    700: "#236E7D",
    800: "#1F5460",
    900: "#1B414B",
    950: "#183239",
    DEFAULT: "#30B0C7",
  },
};

/**
 * Tailwind's stock hues, re-pointed at the iOS ramps.
 *
 * `blue`/`green`/`orange`/`red` were already semantically right and only off
 * brand, so re-pointing them is invisible at the call site: the source still
 * reads `bg-green-100` and now renders iOS green.
 *
 * `yellow`, `amber`, `emerald`, `sky` and `cyan` are aliases onto the hue that
 * carries the same meaning in this system — there is no separate "amber" state,
 * it is a warning, and warnings are orange here.
 *
 * Deliberately NOT aliased: `purple`, `indigo`, `violet`, `fuchsia`, `pink`.
 * Those have no meaning in this design system, so they are removed from the
 * source instead of being silently re-pointed — aliasing them would leave the
 * markup saying "purple" while the screen showed teal, which is worse than the
 * drift it replaces.
 */
export const tailwindHueOverrides = {
  blue: RAMPS.blue,
  sky: RAMPS.blue,
  green: RAMPS.green,
  emerald: RAMPS.green,
  orange: RAMPS.orange,
  amber: RAMPS.orange,
  yellow: RAMPS.orange,
  red: RAMPS.red,
  teal: RAMPS.teal,
  cyan: RAMPS.teal,
};

/** Everything an app needs, ready to spread into `theme.extend.colors`. */
export const iosColors = {
  ...iosNeutrals,
  ...iosSemantic,
  ...iosLegacyAliases,
  ...tailwindHueOverrides,
};

/** Shadows capped at 8% opacity — DESIGN.md "Elevation & Depth". */
export const iosShadows = {
  "ios-sm": "0 2px 8px rgba(0,0,0,0.04)",
  "ios-card": "0 4px 16px rgba(0,0,0,0.06)",
  "ios-float": "0 8px 30px rgba(0,0,0,0.08)",
};
