name = "makanmakan-realtime"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "REALTIME_SESSION", class_name = "RealtimeSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["RealtimeSession"]

[env.staging]
name = "makanmakan-realtime-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "makanmakan-staging"
# TODO: Replace with actual D1 database ID from Cloudflare dashboard
# Run: wrangler d1 create makanmakan-staging
database_id = "STAGING_DB_ID_TO_BE_REPLACED"

[[env.staging.kv_namespaces]]
binding = "CACHE"
# TODO: Replace with actual KV namespace ID from Cloudflare dashboard
# Run: wrangler kv:namespace create "REALTIME_CACHE" --env staging
id = "STAGING_KV_ID_TO_BE_REPLACED"

[env.production]
name = "makanmakan-realtime-prod"

[[env.production.d1_databases]]
binding = "DB"
database_name = "makanmakan-prod"
# TODO: Replace with actual D1 database ID from Cloudflare dashboard
# Run: wrangler d1 create makanmakan-prod
database_id = "PRODUCTION_DB_ID_TO_BE_REPLACED"

[[env.production.kv_namespaces]]
binding = "CACHE"
# TODO: Replace with actual KV namespace ID from Cloudflare dashboard
# Run: wrangler kv:namespace create "REALTIME_CACHE" --env production
id = "PRODUCTION_KV_ID_TO_BE_REPLACED"