#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=7

REPO="erictheng93/Makan-Masak"
ACCOUNT_ID="bdddc08c066a9abc285d75fe5947a468"
ZONE="makanmasak.com"

# Secrets here belong to the `production` GitHub *environment*, not the
# repository. deploy-production.yml declares `environment: production`, so they
# resolve for that job and nothing else; a repository secret would be readable
# by every job in every workflow. The library's set_secret writes repo-level, so
# this wrapper is defined here rather than editing the library.
set_env_secret() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    SKIPPED+=("$name (left blank)")
    warn "skipped $name: no value entered"
    return
  fi
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" --env production --repo "$REPO" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s %s on the production environment\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("$name (gh secret set $name --env production --repo $REPO)")
  warn "could not set $name; do it by hand later"
}

banner "Production deploy: Cloudflare token + GitHub environment secrets"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "GitHub: confirm the production environment"
say "deploy-production.yml runs its deploy job with 'environment: production',"
say "so the secrets have to live on that environment rather than on the repo."
printf '  %s… checking%s\n' "$DIM" "$RESET"
if gh api "repos/$REPO/environments" -q '.environments[].name' 2>/dev/null | grep -qx production; then
  printf '  %s✓ the production environment already exists — nothing to do here%s\n' "$GREEN" "$RESET"
  note "(checked 2026-09-05: 'production' and 'staging' both present)"
else
  warn "no 'production' environment found; create it now"
  open_url "https://github.com/$REPO/settings/environments"
  step "New environment → name it exactly 'production' → Configure environment."
  note "No protection rules are required. Add reviewers later if you want a gate."
  pause "Press Enter once 'production' is listed."
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: create the API token"
say "One custom token covering every binding the ten wrangler.toml files declare."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → Create Custom Token → Get started."
step "Name it something like: makanmasak-github-deploy"
say ""
say "Account permissions — add all nine rows:"
note "  Workers Scripts .............. Edit    (deploy the 5 workers + Durable Objects)"
note "  Workers KV Storage ........... Edit    (11 KV bindings)"
note "  Workers R2 Storage ........... Edit    (4 R2 buckets)"
note "  D1 ........................... Edit    (6 D1 bindings)"
note "  Queues ....................... Edit    (2 queue bindings)"
note "  Vectorize .................... Edit    (1 binding)"
note "  Workers AI ................... Edit    (1 binding)"
note "  Cloudflare Pages ............. Edit    (5 frontends use 'wrangler pages deploy')"
note "  Account Settings ............. Read    (wrangler resolves the account)"
say ""
warn "Cloudflare Pages is the one people miss. Workers Scripts:Edit does NOT cover"
warn "'wrangler pages deploy', and 'pnpm -r run deploy:prod' reaches all five of them."
pause "Press Enter when the nine account rows are in."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Cloudflare: scope the token, then copy it"
say "Still on the same token form."
say ""
say "Zone permissions — add both rows, on $ZONE:"
note "  Workers Routes ............... Edit    (4 custom_domain entries)"
note "  DNS .......................... Edit    (custom_domain creates DNS records)"
say ""
step "Account Resources: Include → the account whose ID is"
note "  $ACCOUNT_ID"
warn "This is NOT the account a local 'wrangler login' resolves to by default."
warn "If you pick the wrong one the token authenticates fine and deploys nothing."
step "Zone Resources: Include → Specific zone → $ZONE"
step "Client IP Address Filtering: leave EMPTY."
note "GitHub-hosted runner addresses are not stable; an IP rule will break deploys."
step "TTL: leave as is, or set a rotation reminder for yourself."
step "Continue to summary → Create Token → copy the token now."
warn "Cloudflare shows the token exactly once."
ask_secret CF_TOKEN "Paste the Cloudflare API token:"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Verify the token before trusting it"
say "This is the check that would have caught the 2026-07-24 failure."
if [[ -z "${CF_TOKEN:-}" ]]; then
  warn "no token entered; skipping verification"
else
  printf '  %s… calling the Cloudflare token verify endpoint%s\n' "$DIM" "$RESET"
  verify=$(curl -sS -H "Authorization: Bearer $CF_TOKEN" \
    "https://api.cloudflare.com/client/v4/user/tokens/verify" 2>/dev/null || echo '{}')
  if printf '%s' "$verify" | grep -q '"success":true'; then
    printf '  %s✓ token is valid and active%s\n' "$GREEN" "$RESET"
  else
    warn "token did not verify. Response:"
    note "  $verify"
    confirm "Continue anyway?" || { warn "stopping so you can re-issue the token"; exit 1; }
  fi

  printf '  %s… checking it can see account %s%s\n' "$DIM" "$ACCOUNT_ID" "$RESET"
  acct=$(curl -sS -H "Authorization: Bearer $CF_TOKEN" \
    "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID" 2>/dev/null || echo '{}')
  if printf '%s' "$acct" | grep -q '"success":true'; then
    printf '  %s✓ the token reaches the right account%s\n' "$GREEN" "$RESET"
  else
    warn "the token cannot see account $ACCOUNT_ID."
    warn "Most likely Account Resources was scoped to a different account."
    confirm "Continue anyway?" || { warn "stopping; fix Account Resources and re-run"; exit 1; }
  fi
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Store the Cloudflare token"
say "Written to the production environment only, never to a local file."
set_env_secret CLOUDFLARE_API_TOKEN "${CF_TOKEN:-}"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Slack: deploy notification webhook"
say "deploy-production.yml posts deploy results to Slack."
say "Reuse an existing incoming webhook, or create one now."
open_url "https://api.slack.com/apps"
step "Your app → Incoming Webhooks → Add New Webhook to Workspace → pick a channel."
step "Copy the https://hooks.slack.com/services/... URL."
note "Leave this blank to skip; the deploy still works, it just posts nothing."
ask_secret SLACK_URL "Paste the Slack webhook URL (or Enter to skip):"
set_env_secret SLACK_WEBHOOK_URL "${SLACK_URL:-}"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "The four public values, then verify"
say "These are not secrets — the account ID is already committed in"
say "apps/api/wrangler.toml:271. They live as environment secrets only because"
say "the workflow reads them from secrets.*. Press Enter to accept each default."
ask ACCOUNT_IN     "CLOUDFLARE_ACCOUNT_ID   [$ACCOUNT_ID]:"
ask PROD_API       "PRODUCTION_URL          [https://api.makanmasak.com]:"
ask PROD_CUSTOMER  "PRODUCTION_CUSTOMER_URL [https://makanmasak.com]:"
ask PROD_KITCHEN   "PRODUCTION_KITCHEN_URL  [https://kitchen.makanmasak.com]:"
set_env_secret CLOUDFLARE_ACCOUNT_ID   "${ACCOUNT_IN:-$ACCOUNT_ID}"
set_env_secret PRODUCTION_URL          "${PROD_API:-https://api.makanmasak.com}"
set_env_secret PRODUCTION_CUSTOMER_URL "${PROD_CUSTOMER:-https://makanmasak.com}"
set_env_secret PRODUCTION_KITCHEN_URL  "${PROD_KITCHEN:-https://kitchen.makanmasak.com}"
say ""
say "What the production environment holds now:"
gh secret list --env production --repo "$REPO" 2>/dev/null | sed 's/^/    /' \
  || warn "could not list; check https://github.com/$REPO/settings/environments"

finish

printf '  %sNext:%s trigger a real deploy to prove it end to end.\n' "$BOLD" "$RESET"
cat <<'NEXT'
  The workflow is workflow_dispatch and requires a typed confirmation:

    gh workflow run deploy-production.yml -f confirm="DEPLOY PRODUCTION"
    gh run watch $(gh run list --workflow=deploy-production.yml -L1 \
      --json databaseId -q '.[0].databaseId')

  apps/backup-scheduler is the first package that "pnpm -r run deploy:prod"
  reaches, so that is where a bad token surfaces first.

NEXT
