CREATE INDEX `idx_cash_movements_shift` ON `cash_movements` (`shift_id`);--> statement-breakpoint
CREATE INDEX `idx_cash_movements_register` ON `cash_movements` (`register_id`);--> statement-breakpoint
CREATE INDEX `idx_cash_movements_type` ON `cash_movements` (`shift_id`,`type`);--> statement-breakpoint
CREATE INDEX `idx_cash_movements_created` ON `cash_movements` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_cash_registers_restaurant` ON `cash_registers` (`restaurant_id`);--> statement-breakpoint
CREATE INDEX `idx_cash_registers_active` ON `cash_registers` (`restaurant_id`,`is_active`);--> statement-breakpoint
CREATE INDEX `idx_cash_shifts_register` ON `cash_shifts` (`register_id`);--> statement-breakpoint
CREATE INDEX `idx_cash_shifts_operator` ON `cash_shifts` (`operator_id`);--> statement-breakpoint
CREATE INDEX `idx_cash_shifts_status` ON `cash_shifts` (`register_id`,`status`);--> statement-breakpoint
CREATE INDEX `idx_cash_shifts_started` ON `cash_shifts` (`started_at`);--> statement-breakpoint
CREATE INDEX `idx_receipts_order` ON `receipts` (`order_id`);--> statement-breakpoint
CREATE INDEX `idx_receipts_register` ON `receipts` (`register_id`);--> statement-breakpoint
CREATE INDEX `idx_receipts_shift` ON `receipts` (`shift_id`);--> statement-breakpoint
CREATE INDEX `idx_receipts_print_status` ON `receipts` (`print_status`);--> statement-breakpoint
CREATE INDEX `idx_refunds_order` ON `refunds` (`original_order_id`);--> statement-breakpoint
CREATE INDEX `idx_refunds_register` ON `refunds` (`register_id`);--> statement-breakpoint
CREATE INDEX `idx_refunds_shift` ON `refunds` (`shift_id`);--> statement-breakpoint
CREATE INDEX `idx_refunds_status` ON `refunds` (`status`);--> statement-breakpoint
CREATE INDEX `idx_shift_reports_shift` ON `shift_reports` (`shift_id`);--> statement-breakpoint
CREATE INDEX `idx_shift_reports_register` ON `shift_reports` (`register_id`);--> statement-breakpoint
CREATE INDEX `idx_shift_reports_operator` ON `shift_reports` (`operator_id`);--> statement-breakpoint
CREATE INDEX `idx_shift_reports_generated` ON `shift_reports` (`generated_at`);--> statement-breakpoint
CREATE INDEX `idx_group_activity_logs_group_order` ON `group_activity_logs` (`group_order_id`);--> statement-breakpoint
CREATE INDEX `idx_group_activity_logs_action` ON `group_activity_logs` (`group_order_id`,`action`);--> statement-breakpoint
CREATE INDEX `idx_group_activity_logs_created` ON `group_activity_logs` (`created_at`);--> statement-breakpoint
CREATE INDEX `idx_group_cart_items_group_order` ON `group_cart_items` (`group_order_id`);--> statement-breakpoint
CREATE INDEX `idx_group_cart_items_member` ON `group_cart_items` (`member_id`);--> statement-breakpoint
CREATE INDEX `idx_group_cart_items_status` ON `group_cart_items` (`group_order_id`,`status`);--> statement-breakpoint
CREATE INDEX `idx_group_members_group_order` ON `group_members` (`group_order_id`);--> statement-breakpoint
CREATE INDEX `idx_group_members_session` ON `group_members` (`session_id`);--> statement-breakpoint
CREATE INDEX `idx_group_members_user` ON `group_members` (`user_id`);--> statement-breakpoint
CREATE INDEX `idx_group_members_active` ON `group_members` (`group_order_id`,`is_active`);--> statement-breakpoint
CREATE INDEX `idx_group_orders_restaurant_status` ON `group_orders` (`restaurant_id`,`status`);--> statement-breakpoint
CREATE INDEX `idx_group_orders_status_created` ON `group_orders` (`status`,`created_at`);--> statement-breakpoint
CREATE INDEX `idx_group_orders_table` ON `group_orders` (`table_id`);--> statement-breakpoint
CREATE INDEX `idx_group_orders_expires` ON `group_orders` (`expires_at`);--> statement-breakpoint
CREATE INDEX `idx_share_codes_type_resource` ON `share_codes` (`type`,`resource_id`);--> statement-breakpoint
CREATE INDEX `idx_share_codes_active_expires` ON `share_codes` (`is_active`,`expires_at`);--> statement-breakpoint
CREATE INDEX `idx_split_bills_group_order` ON `split_bills` (`group_order_id`);--> statement-breakpoint
CREATE INDEX `idx_split_bills_member` ON `split_bills` (`member_id`);--> statement-breakpoint
CREATE INDEX `idx_split_bills_payment_status` ON `split_bills` (`group_order_id`,`payment_status`);