ALTER TABLE `restaurants` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `restaurants` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `restaurants` ADD `deleted_at_ms` integer;--> statement-breakpoint
ALTER TABLE `users` ADD `last_login_at_ms` integer;--> statement-breakpoint
ALTER TABLE `users` ADD `password_changed_at_ms` integer;--> statement-breakpoint
ALTER TABLE `users` ADD `email_verified_at_ms` integer;--> statement-breakpoint
ALTER TABLE `users` ADD `phone_verified_at_ms` integer;--> statement-breakpoint
ALTER TABLE `users` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `users` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `users` ADD `deleted_at_ms` integer;--> statement-breakpoint
ALTER TABLE `categories` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `categories` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `categories` ADD `deleted_at_ms` integer;--> statement-breakpoint
ALTER TABLE `menu_items` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `menu_items` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `menu_items` ADD `deleted_at_ms` integer;--> statement-breakpoint
ALTER TABLE `tables` ADD `occupied_at_ms` integer;--> statement-breakpoint
ALTER TABLE `tables` ADD `estimated_free_at_ms` integer;--> statement-breakpoint
ALTER TABLE `tables` ADD `last_cleaned_at_ms` integer;--> statement-breakpoint
ALTER TABLE `tables` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `tables` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `tables` ADD `deleted_at_ms` integer;--> statement-breakpoint
ALTER TABLE `orders` ADD `confirmed_at_ms` integer;--> statement-breakpoint
ALTER TABLE `orders` ADD `preparing_at_ms` integer;--> statement-breakpoint
ALTER TABLE `orders` ADD `ready_at_ms` integer;--> statement-breakpoint
ALTER TABLE `orders` ADD `delivered_at_ms` integer;--> statement-breakpoint
ALTER TABLE `orders` ADD `paid_at_ms` integer;--> statement-breakpoint
ALTER TABLE `orders` ADD `cancelled_at_ms` integer;--> statement-breakpoint
ALTER TABLE `orders` ADD `reviewed_at_ms` integer;--> statement-breakpoint
ALTER TABLE `orders` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `orders` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `audit_logs` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `employee_leave_balances` ADD `carryover_expires_at_ms` integer;--> statement-breakpoint
ALTER TABLE `employee_leave_balances` ADD `adjusted_at_ms` integer;--> statement-breakpoint
ALTER TABLE `employee_leave_balances` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `employee_leave_balances` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_approval_rules` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_approval_rules` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_calendar_events` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_calendar_events` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_requests` ADD `final_approved_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_requests` ADD `rejected_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_requests` ADD `cancelled_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_requests` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_requests` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_requests` ADD `submitted_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_types` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `leave_types` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `employee_availability` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `employee_availability` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `employee_schedules` ADD `clock_in_time_ms` integer;--> statement-breakpoint
ALTER TABLE `employee_schedules` ADD `clock_out_time_ms` integer;--> statement-breakpoint
ALTER TABLE `employee_schedules` ADD `confirmed_at_ms` integer;--> statement-breakpoint
ALTER TABLE `employee_schedules` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `employee_schedules` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `schedule_swap_requests` ADD `accepted_at_ms` integer;--> statement-breakpoint
ALTER TABLE `schedule_swap_requests` ADD `approved_at_ms` integer;--> statement-breakpoint
ALTER TABLE `schedule_swap_requests` ADD `rejected_at_ms` integer;--> statement-breakpoint
ALTER TABLE `schedule_swap_requests` ADD `expires_at_ms` integer;--> statement-breakpoint
ALTER TABLE `schedule_swap_requests` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `schedule_swap_requests` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `scheduling_conflicts` ADD `resolved_at_ms` integer;--> statement-breakpoint
ALTER TABLE `scheduling_conflicts` ADD `detected_at_ms` integer;--> statement-breakpoint
ALTER TABLE `scheduling_conflicts` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `scheduling_conflicts` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `scheduling_rules` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `scheduling_rules` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `shift_templates` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `shift_templates` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `cash_movements` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `cash_registers` ADD `last_maintenance_at_ms` integer;--> statement-breakpoint
ALTER TABLE `cash_registers` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `cash_registers` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `cash_shifts` ADD `started_at_ms` integer;--> statement-breakpoint
ALTER TABLE `cash_shifts` ADD `ended_at_ms` integer;--> statement-breakpoint
ALTER TABLE `receipts` ADD `printed_at_ms` integer;--> statement-breakpoint
ALTER TABLE `receipts` ADD `last_reprint_at_ms` integer;--> statement-breakpoint
ALTER TABLE `receipts` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `refunds` ADD `processed_at_ms` integer;--> statement-breakpoint
ALTER TABLE `refunds` ADD `completed_at_ms` integer;--> statement-breakpoint
ALTER TABLE `shift_reports` ADD `generated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `group_activity_logs` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `group_cart_items` ADD `added_at_ms` integer;--> statement-breakpoint
ALTER TABLE `group_cart_items` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `group_members` ADD `joined_at_ms` integer;--> statement-breakpoint
ALTER TABLE `group_members` ADD `last_active_at_ms` integer;--> statement-breakpoint
ALTER TABLE `group_members` ADD `left_at_ms` integer;--> statement-breakpoint
ALTER TABLE `group_orders` ADD `expires_at_ms` integer;--> statement-breakpoint
ALTER TABLE `group_orders` ADD `locked_at_ms` integer;--> statement-breakpoint
ALTER TABLE `group_orders` ADD `completed_at_ms` integer;--> statement-breakpoint
ALTER TABLE `group_orders` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `group_orders` ADD `updated_at_ms` integer;--> statement-breakpoint
ALTER TABLE `share_codes` ADD `expires_at_ms` integer;--> statement-breakpoint
ALTER TABLE `share_codes` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `split_bills` ADD `paid_at_ms` integer;--> statement-breakpoint
ALTER TABLE `split_bills` ADD `created_at_ms` integer;--> statement-breakpoint
ALTER TABLE `split_bills` ADD `updated_at_ms` integer;