# Cloudflare Workers configuration
name = "makanmakan-api"
main = "src/index.ts"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

# Variables (non-sensitive only)
[vars]
NODE_ENV = "development"
API_VERSION = "v1"
API_BASE_URL = "http://localhost:8787"

# SECURITY NOTE: JWT_SECRET should be set via 'wrangler secret put JWT_SECRET'
# Never put sensitive values in wrangler.toml as they are visible in version control

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "makanmakan-local"
database_id = "local"

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE_KV"
id = "makanmakan-cache-dev"
preview_id = "makanmakan-cache-preview"

# KV namespace for JWT token blacklisting (security)
[[kv_namespaces]]
binding = "TOKEN_BLACKLIST"
id = "makanmakan-tokens-dev"
preview_id = "makanmakan-tokens-preview"

# R2 bucket for file storage
[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "makanmakan-images"

# Durable Objects for real-time features
[[durable_objects.bindings]]
name = "REALTIME_ORDERS"
class_name = "RealtimeOrders"

# Queue for background jobs
[[queues.producers]]
binding = "JOB_QUEUE"
queue = "makanmakan-jobs"

# Staging environment
[env.staging]
name = "makanmakan-api-staging"
vars = { NODE_ENV = "staging", API_VERSION = "v1", API_BASE_URL = "https://api-staging.makanmakan.com" }

[[env.staging.d1_databases]]
binding = "DB"
database_name = "makanmakan-staging"
# TODO: Replace with actual D1 database ID from Cloudflare dashboard
# Run: wrangler d1 create makanmakan-staging
database_id = "STAGING_DB_ID_TO_BE_REPLACED"

[[env.staging.kv_namespaces]]
binding = "CACHE_KV"
id = "makanmakan-cache-staging"

[[env.staging.kv_namespaces]]
binding = "TOKEN_BLACKLIST"
id = "makanmakan-tokens-staging"

# Production environment  
[env.production]
name = "makanmakan-api-prod"
vars = { NODE_ENV = "production", API_VERSION = "v1", API_BASE_URL = "https://api.makanmakan.com" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "makanmakan-prod"
# TODO: Replace with actual D1 database ID from Cloudflare dashboard
# Run: wrangler d1 create makanmakan-prod
database_id = "PRODUCTION_DB_ID_TO_BE_REPLACED"

[[env.production.kv_namespaces]]
binding = "CACHE_KV"
id = "makanmakan-cache-prod"

[[env.production.kv_namespaces]]
binding = "TOKEN_BLACKLIST"
id = "makanmakan-tokens-prod"

# Build configuration
[build]
command = "npm run build"

# Limits and performance
[limits]
cpu_ms = 1000